language: ruby
notifications:
  email: false
rvm:
  - 2.2.2
script:
  - bundle exec rspec
  - bundle exec yard stats | grep "100.00% documented"
env:
  matrix:
    secure: U1hllkLS9Mf9aQyY91oZtLmAHd28o5jCwLO79L2qdMnHBGVQCEtodZdO8dbuQyqAtwazNZNJHtJQvMPbYs6YoyT3uVrJ5fJUsgLIm2WLOf67ADA4ZjYRrRF+n9uoIkH1veOg44VBWCVNUVGygXsC0zo1tCCroewtz1eEUuQ12jLg36X7IbQCillXN0zqzckkB7ABd9ZokcqOZgsSiq/RL0AmvsbSMdCG89vMwMySWOyOKue8Okee7RhOZAP6XiZ/jc8eIZn6RlGuvae7c9DMqMF0auL2JYCn8T/fYZD05np2I7gszNXmLiYiFxB33JUh6iFrLhLYdx3JflDNS9tPAawfiy6WkVmz87lcgcWjvDWEowDfIZIE5BUEpSJvQmprsgzV1F+c1QmD1/hE9EGa6Mld0H3ebuKfLuJBWznBWdzF+wprHvbYNUYOqM7LCu64/1oZrS+D35foCXNf95AjK7OOblTIY3wF1JY4KzRArUz/jSVikYsN8v7v5XENxD5ly2u6b+PP/z1h3SYWJZIlRrmvEvHoEiCOMNU+0VKT1h/aZ2kKHt9nIgI9FN3c9h4XZt37/MZupq9KExczVzWeIl2cADYgRcYDvfB2b3yuBG9Wjlcp27A1VQ+xKskEdIDRJs7mJ+tyZJr+0d3xOnJSVFG1P7KI/t5Zzah9/SM5kh0=
